version: '3'
services:
  app: &app_base
    container_name: myapp
    build: .
    volumes:
      - ./myapp:/root/myapp
      - bundle_install:/root/myapp/vendor/bundle
      - tmp_cache:/root/myapp/tmp/cache
      - ./log:/var/log/myapp
      - ./dotfiles:/root/dotfiles
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: development
      CACHE_STORE_URI: redis://redis:6379/0/cache
      SESSION_STORE_URI: redis://redis:6379/0/session
      COMMAND: bundle exec rails s
  mysql:
    container_name: myapp_db
    image: "mysql:5.7"
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    container_name: myapp_redis
    image: "redis"
    ports:
      - "6379:6379"
  spring:
    <<: *app_base
    container_name: myapp_spring
    command: ["/root/scripts/spring.sh"]
    ports: []
    tty: false
    stdin_open: false
volumes:
  mysql_db:
    driver: local
  bundle_install:
    driver: local
  tmp_cache:
    driver: local
